# Change these first
owner: auto-fortisase # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: FortiSASE SIA Cloud
    url: https://portal.prod.fortisase.com/
  - name: FortiSASE SIA Edge Canada West (Vancouver)
    url: https://mgmt-fos001-region1.prod.fortisase.com:10443/
    __dangerous__insecure: true
  - name: FortiSASE SIA Edge Canada East (Ottawa)
    url: https://mgmt-fos001-region2.prod.fortisase.com:10443/
    __dangerous__insecure: true
  - name: FortiSASE SIA Edge France (Valbonne)
    url: https://mgmt-fos001-region3.prod.fortisase.com:10443/
    __dangerous__insecure: true
  - name: FortiSASE SIA Edge Japan (Tokyo)
    url: https://mgmt-fos001-region4.prod.fortisase.com:10443/
    __dangerous__insecure: true
  - name: ForitStack API Canada West (Vancouver)
    url: https://fortistackapi-nova-west.fortisase.com:5000/v3
  - name: FortiStack API Canada East (Ottawa)
    url: https://fortistackapi-nova-east.fortisase.com:5000/v3
  - name: FortiStack API France (Valbonne)
    url: https://fortistackapi-nova-fr.fortisase.com:5000/v3
  - name: FortiStack API Japan (Tokyo)
    url: https://fortistackapi-nova-jp.fortisase.com:5000/v3
#  - name: THIS IS A TEST
#    url: https://down.fortisase.com/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.fortisase.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/auto-fortisase/upptime/master/assets/icons/fortinet.png
  name: FortiSASE SIA Status
  introTitle: "**FortiSASE SIA** services status"
  introMessage: This is a service status page which uses **real-time** data to display service status.
  navbar:
    - title: Status
      href: /
    - title: FortiSASE SIA
      href: https://portal.prod.fortisase.com/
    - title: Contact
      href: https://www.fortinet.com/support/contact
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
